name: External Semantic Layer Upload
run-name: ${{ github.actor }} is uploading an external semantic layer 🚀
on: [push]
jobs:
  External-Semantic-Layer-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Archive repository
      run: git archive -o repo.zip HEAD

    - name: Send archive via curl
      run: |
        response=$(curl -o /dev/null -s -w "%{http_code}" -X POST \
          -F "data=@repo.zip" \
          https://dev-app-antelope.hex.tech/api/v1/semantic-layer \
          -H "Authorization: Bearer d773ff0d5f1fea8c396cb2a3956ec9af56a675fbe0307038c244886f7683297a8d32df5ef4d95fee3907e41d61f63212")
        if [ "$response" -ne 201 ]; then
          echo "Server responded with code $response"
          exit 1
        fi
